export const COUNT_INCREASE = 'COUNT_INCREASE'
export const COUNT_DECREASE = 'COUNT_DECREASE'

export const REQUEST_USDA_API_PENDING = 'REQUEST_USDA_API_PENDING';
export const REQUEST_USDA_API_SUCCESS = 'REQUEST_USDA_API_SUCCESS';
export const REQUEST_USDA_API_FAILED = 'REQUEST_USDA_API_FAILED';